=== giellalt/dict-nob-fin/dtd/nobfin.dtd
<!ELEMENT e ( lg, mg+, ig*, xhtml:script? ) >
<!ATTLIST e reverse NMTOKEN #IMPLIED >
<!ATTLIST e src CDATA #IMPLIED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l pos ( A | Adv | CC | CS | Interj | N |
                  Num | Phrase | Pr | Pron | Prop | V ) #REQUIRED >
<!ATTLIST l type (Prop) #IMPLIED >

<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'>

<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >

<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a|i)*>
<!ELEMENT a (#PCDATA)>

<!ELEMENT lg ( l ) >

<!ELEMENT mg ( re?,  tg+ ) >

<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xml:lang (nob) #IMPLIED>
<!ATTLIST r id (nobfin) #IMPLIED>

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t pos ( A | Adv | CC | CS | Interj | N | Num |
                  Po | Pr | Pron | V | suff ) #IMPLIED >
<!ATTLIST t type ( Prop | grammar ) #IMPLIED >
<!ATTLIST t t_type ( Phrase | expl ) #IMPLIED >


<!--
<!ELEMENT te ( #PCDATA ) >
<!ATTLIST te type ( grammar ) #IMPLIED >
-->
<!ELEMENT tg (re?, t+,  xg* ) >

<!ATTLIST tg comment CDATA #IMPLIED >
<!ATTLIST tg xml:lang NMTOKEN #FIXED "fin" >

<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->
<!ATTLIST re
    xml:lang ( nob | fin | lat ) #IMPLIED
>
<!ATTLIST re x ( fad ) #IMPLIED >
<!ATTLIST re comment CDATA #IMPLIED >

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >


<!-- Idiom phrases, faste uttrykk -->
<!ELEMENT ig ( i+, id?, it+)+ >
<!ELEMENT i (#PCDATA) >
<!ATTLIST i src CDATA #IMPLIED >
<!ELEMENT id (#PCDATA) >
<!ELEMENT it (#PCDATA) >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-nob-fin/src/CS_nobfin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/nobfin.dtd">
<r id="nobfin" xml:lang="nob">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Trond Trosterud and Kirsti Kuosa at UiT. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="CS">at ikke</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">ettei</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">at</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">että</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">at</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">että</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">da</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">kun</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">dersom</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">jos</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">enn</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">entä</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">enn</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">kuin</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">fordi</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">koska</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">fordi</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">sillä</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">hvis</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">jos</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">når</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">koska</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">når</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">kun</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">om</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">jos</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">som</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">kuin</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-nob-fin/src/CC_nobfin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/nobfin.dtd">
<r id="nobfin" xml:lang="nob">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Trond Trosterud and Kirsti Kuosa at UiT. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="CC">både</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">sekä</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">da</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">kun</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">eller</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">eli</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">eller</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">eller</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">eller</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">vai</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">eller</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">vain</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">enn</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">kun</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">enten ... eller</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">joko ... tai</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">enten</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">joko</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">hvis</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">jos</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">men</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">mutta</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">når</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">kun</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">og</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">ja</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">om</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">jos</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">samt</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">ja</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">selv om</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">vaikka</t>
            <xg>
               <x/>
               <xt/>
            </xg>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-nob-fin/src/Interj_nobfin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/nobfin.dtd">
<r id="nobfin" xml:lang="nob">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Trond Trosterud and Kirsti Kuosa at UiT. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="Interj">ha det</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Interj">heippa</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Interj">hei</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Interj">moi</t>
         </tg>
      </mg>
   </e>
</r>
